name: build

on:
  push:
    branches:
      - mc*

jobs:
  main:
    runs-on: ubuntu-latest      
    permissions:
      contents: read
      packages: write

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'      

    - name: Data Generation
      uses: gradle/gradle-build-action@v2
      with:
        arguments: runData
        cache-read-only: false
      env:
        BUILDNUM: ${{ github.run_number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build publish curseforge modrinth
        cache-read-only: false
      env:
        BUILDNUM: ${{ github.run_number }}
        KEY_CURSEFORGE: ${{ secrets.KEY_CURSEFORGE }}
        KEY_MODRINTH: ${{ secrets.KEY_MODRINTH }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAVEN_USER: ${{ secrets.MAVEN_USER }}
        MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
        